name: Trackable Change
description: >-
  Please only use this, if you've been advised to do so after discussion. Thanks! 🙏
body:
  - type: textarea
    attributes:
      label: What's happening?
      description: A clear and concise description of the current behaviour.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducer
      description: Steps to reproduce the issue. Please attach screenshots as well.
      value: |
        1. Run `nox -s fetch -- sampleproject`.
        1. ???
        1. Profit.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expectation
      description: A clear and concise description of what should've happened.
    validations:
      required: true
